platform :ios, '10.0'

use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => true

#
# Targets

workspace 'CEFoundation'

target 'Example iOS' do
    project 'Examples/Examples'
    pod 'CEFoundation', :path => './'
    
    pod 'IGListKit'
    pod 'AFNetworking', '4.0.1'
    pod 'YYModel'
    pod 'MBProgressHUD'
    pod 'Reachability'
    pod 'Masonry'
    pod 'FMDB'

    pod 'SnapKit'
    pod 'Alamofire'
    pod 'RxSwift'
end

target 'Tests iOS' do
    project 'CEFoundation'
    pod 'CEFoundation', :path => './'
end
