platform :ios, '10.0'

use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => true

#
# Targets

workspace 'CEUIKitCore'

target 'Example iOS' do
    project 'Examples/Examples'
    pod 'CEUIKitCore', :path => './'

    pod 'IGListKit'
    pod 'AFNetworking'
    pod 'YYModel'
    pod 'MBProgressHUD'
    pod 'Reachability'
    pod 'Masonry'
    pod 'FMDB'

    pod 'SnapKit'
    pod 'Alamofire'
    pod 'RxSwift'
end

target 'Tests iOS' do
    project 'CEUIKitCore'
    pod 'CEUIKitCore', :path => './'
end
